# Generated by Django 5.1.3 on 2024-11-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='distance',
        ),
    ]
